### ISSUE TITLE
Raster execution request missing output_params

### ISSUE THREAD

**Issue by pchevali** [GeoNode/geonode-importer#236]
Hi, 

When calling through API the importer endpoints, and checking the import status by polling the execution request I found out that for vector layer, the "output_params" key gets updated with the "detail_url" link, but for raster we get an empty object after the request is finished.

After looking at the code it seems that for rasters the detail_url is updated after the execution request is saved.

I fixed it locally by moving "exec.save()" after the update of the execution request see :

https://github.com/GeoNode/geonode-importer/blob/master/importer/handlers/common/raster.py#L198

I am using this detail_url to retrieve the pk of the uploaded resource, wouldn't it be nice to have the pk returned after the import process is done ?

**Comment by mattiagiupponi** [comment]
Hi @pchevali 
Thanks for opening the issue. Is an issue and i guess you fix is correct. If you like you can submit a PR with it.

> I am using this detail_url to retrieve the pk of the uploaded resource, wouldn't it be nice to have the pk returned after the import process is done ?

Consider that for now, the detail_url is used by the geonode UI to redirect the user to the dataset after the upload. the button "View Dataset" redirect the user to it.

So far there is not much use case for having the PK, but is something that can be added for sure in the future

**Comment by pchevali** [comment]
Hi @mattiagiupponi 

OK, I will submit a PR 
For the PK, am currently automating dataset import through API, and although that I can have the pk by parsing the detail_url, it would be interesting to have it after the import is finished. Otherwise, the workaround is to query the catalog with the dataset name but in the case that there is already a dataset with the same name, we cannot know exactly what is the pk of the imported dataset.

**Comment by mattiagiupponi** [comment]
That's sound like a nice use case.
Consider that the output_params (and the detail URL) is always performed as last step.
My only doubt here is how to handle the PK for GPKG and KML since they can import multiple dataset with one single upload.
I guess we can have a new key in the output_params [here](https://github.com/GeoNode/geonode-importer/blob/master/importer/handlers/common/raster.py#L200) for raster and [here ](https://github.com/GeoNode/geonode-importer/blob/269ec258b9e3052ac117646e42a038c79ce280be/importer/handlers/common/vector.py#L227) for vector where we put in a list all the PK imported.
Something like this:

```
resources = ResourceHandlerInfo.objects.filter(execution_request=_exec)
_exec.output_params.update(
            **{
                "detail_url": [ x.resource.detail_url for x in resources ],
                "pk": [ x.resource.detail_url for x in resources ],
            }
        )
```
