### ISSUE TITLE
CRS parsing is not correctly handled for CSV files

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-importer#242]
@mattiagiupponi maybe it's a regression but from my tests the upload of CSV is always failing due to exceptions thrown inside `BaseVectorFileHandler.identify_authority()`.

With CSV files layer.GetSpatialRef() returns always `None`, so both the try and the exception handler will fail at retrieving the CRS.
I think `BaseVectorFileHandler.identify_authority()` should be overridden by the CSV handler and, for simple geom fields (lat/lon) the CRS will be forced to `EPSG:4326`

**Comment by mattiagiupponi** [comment]
For the CSV is indeed force to `EPSG:4326`
In this case with the introduction of this fix https://github.com/GeoNode/geonode-importer/issues/233. For the CSV that checks is not useful since the authority is extracted later. We can justlet the CSV skip that part. Once the CSV is validated we are good to go
